version: '2.1'
orbs:
  node: circleci/node@4.2
jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
  test:
    executor:
      name: node/default
      tag: '12.18'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: RUN YARN tests
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
workflows:
  test_my_app:
    jobs:
      - test